clear;
pkg load symbolic;
##syms lambda_w lambda_e Sw Se T2i T2_imenys1 T2_imes1 deltax alfa1i T1i Sl2int Sl2ext alfa3i T3i;
##eq=-lambda_w*(T2_imenys1-T2i)*Sw/deltax+lambda_e*(T2_imes1-T2i)*Se/deltax+alfa1i*(T1i-T2i)*Sl2int-alfa3i*(T2i-T3i)*Sl2ext==0;
##%sol=solve(eq,T2i);
data=csvread('Treball_sortida.csv');
data(1,:)=[];
%plot(data(:,2),data(:,3));
%plot(data(:,2),data(:,4));
plot(data(1:end-1,2),data(1:end-1,13));
